---
name: "Build and publish"
description: "Publishes a Docker image to GitHub Container Registry"
inputs:
  github_token:
    description: "The token used when calling GitHub API"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.image_name }}
        tags: |
          type=raw,value={{branch}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ${{ env.dir_name }}
        file: ${{ env.dockerfile }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          REGISTRY=ghcr.io/

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.image_name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
