#!/usr/bin/env bash

set -e

DIR=$1
shift
FILE="$DIR/Dockerfile"
NAME="${DIR//\//-}"
LABEL="yettoapp/$NAME"
TAG="main"
echo "Building $LABEL tagged as $TAG ($FILE)"

cd "$DIR"
docker build -t "$LABEL:$TAG" "$@" .
