name: Build Docker image

on:
  registry_package:

env:
  REGISTRY: ghcr.io

permissions:
  id-token: write
  contents: read
  packages: write
  attestations: write

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action data to a Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_INFRA_WEBHOOK_URL }}
          webhook-type: webhook-trigger
