name: Updates
on:
  workflow_dispatch:
    inputs:
      action:
        required: true
        type: string
      value:
        required: false
        type: string

jobs:
  update:
    name: Update app
    uses: yettoapp/actions/.github/workflows/updater.yml@main
    with:
      action: ${{ inputs.action }}
      value: ${{ inputs.value }}
